### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mymusise** [sprat/yuicompressor#1]
Hi, I'm a Web Developer with django,yesterday i reset my system because a stupid action.After recovery my project,I found a error after running **python manage.py collectstatic** 
`Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/usr/local/lib/python2.7/dist-packages/pipeline/storage.py", line 26, in post_process
    packager.pack_stylesheets(package)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 76, in compress_css
    css = getattr(compressor(verbose=self.verbose), 'compress_css')(css)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/yui.py", line 16, in compress_css
    return self.compress_common(css, 'css', settings.PIPELINE_YUI_CSS_ARGUMENTS)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/yui.py", line 10, in compress_common
    return self.execute_command(command, content)
  File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 244, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: Traceback (most recent call last):
  File "/usr/local/bin/yuicompressor", line 9, in <module>
    load_entry_point('yuicompressor==2.4.2', 'console_scripts', 'yuicompressor')()
  File "/usr/local/lib/python2.7/dist-packages/yuicompressor/__init__.py", line 13, in main
    os.execlp("java", name, "-jar", get_jar_filename(), *sys.argv[1:])
  File "/usr/lib/python2.7/os.py", line 327, in execlp
    execvp(file, args)
  File "/usr/lib/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
`

but I Found the reason was I didn't install Java at all ! [cry face]

So I suggest you can check the Java environment in **Setup** 

thank you for your contribution :)

**Comment by sprat** [comment]
By looking at the stacktrace, we can easily figure that java is missing. Furthermore, it's explicitly stated in the documentation that Java is required. So I think it's not worth adding some code. And you know, yuicompressor is quite dead actually.
